# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "usb_storage" "uas" "sd_mod" ];
  boot.blacklistedKernelModules = [ "rtw88_8822ce" ]; 
  boot.kernelModules = [ "kvm-amd" "r8169" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "sippet-os/ephemeral/slash";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/26A8-0C7E";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    { device = "sippet-os/ephemeral/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "sippet-os/ephemeral/home";
      fsType = "zfs";
    };

  fileSystems."/persist" =
    { device = "sippet-os/eternal/persist";
      fsType = "zfs";
    };

  fileSystems."/keystore" =
    { device = "sippet-os/ephemeral/keystore";
      fsType = "zfs";
    };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
